### ISSUE TITLE
The control display is incomplete, It is recommended to use TControllist.

### ISSUE THREAD

**Issue by laoqiuqiu** [AliDehbansiahkarbon/GithubTrendings#2]
https://img.picui.cn/free/2024/11/05/6729bc0a74632.png

**Comment by AliDehbansiahkarbon** [comment]
Has been replaced with ControlList, plus many other improvements.
Please try again, I hope it works better now.

**Comment by laoqiuqiu** [comment]
The control still displays incompletely.

**Comment by AliDehbansiahkarbon** [comment]
Ok.
I cannot replicate the issue, even when I increased the Windows text size beyond 100%, it appeared fine.
So I just fixed that link label's font size, please try it again.

**Comment by AliDehbansiahkarbon** [comment]
Any news?
