### ISSUE TITLE
Correção na abertura do link do repositorio

### ISSUE THREAD

**Issue by Rtrevisan20** [AliDehbansiahkarbon/GithubTrendings#4]
Quando clica no nome do respoditório para abrir no navegador sempre abre o link do ultimo repositório. 
Correção muito simples: passar na tag do item LinkLabel_RepositoryLink o parametro AIndex da procedure AddRepository.
Simplificar a abertura da Url no método LinkLabel_RepositoryLinkClick:
Url := cGitHubURL +'/' + FRepositoryList.Items[TLinkLabel(Sender).Tag].Author + '/' +  FRepositoryList.Items[TLinkLabel(Sender).Tag].RepoName;
var Url := FRepositoryList.Items[TLinkLabel(Sender).Tag].RepoURL;

Correction in opening the repository link
When you click on the repository name to open it in the browser, it always opens the link to the last repository.
Very simple fix: pass the AIndex parameter of the AddRepository procedure to the LinkLabel_RepositoryLink item tag.
Simplify opening the URL in the LinkLabel_RepositoryLinkClick method:
Url := cGitHubURL +'/' + FRepositoryList.Items[TLinkLabel(Sender).Tag].Author + '/' +  FRepositoryList.Items[TLinkLabel(Sender).Tag].RepoName;
var Url := FRepositoryList.Items[TLinkLabel(Sender).Tag].RepoURL;

**Comment by AliDehbansiahkarbon** [comment]
Fixed.
Thank you.
